#!/usr/bin/python3

import argparse
import C_build_script.make as make
import shutil
import os
import sys

from pathlib import Path


def main():

    argparser = argparse.ArgumentParser()
    argparser.add_argument("-s", action='store', type=str, metavar="SOURCE",    help="Source file to generate executable from")
    argparser.add_argument("-o", action='store', type=str, metavar="EXE NAME",  help="Executable output name")
    argparser.add_argument("-a", action='store_true', help="Build all and skip linking")
    argparser.add_argument("-d", action='store_true', help="Sets build to debug mode")
    argparser.add_argument("-c", action='store_true', help="Cleans all output files")
    args = argparser.parse_args()

    if args.c:
        if os.path.exists("bin"):
            print("Removing 'bin/'")
            shutil.rmtree("bin")
        if os.path.exists("objects"):
            print("Removing 'objects/'")
            shutil.rmtree("objects")
        if os.path.exists("objects-debug"):
            print("Removing 'objects-debug/'")
            shutil.rmtree("objects-debug")

    dependency_mapping = {

    }

    # Copy folders directly into bin
    resource_mappings = {

    }

    if args.s or args.a:
        source_main = "*.cpp" if args.a else Path(args.s).relative_to("src")
        config = {
            "COMPILER":             "clang++",
            "LINKER_FLAGS":         "-pthread",
            "SOURCE_DIR":           "src/",
            "SOURCE_MAIN":          source_main,
            "RESOURCES":            resource_mappings,
            "DEPEND_MAPPING":       dependency_mapping,
            "COMPILATION_DATABASE": True,
            # globs for source_main should skip linker to avoid multiple main linkage
            "SKIP_LINKER":          True if "*" in str(source_main) else False
        }

        if args.d:
            config["COMPILER_FLAGS"] = "-std=c++23 -Wall -Wextra -Wpedantic -g -O0 -DDEBUG -Wno-language-extension-token"
            config["LINKER_FLAGS"] += " -g"
            config["OBJECT_DIR"] = "./objects-debug/"
            config["EXE_FILE"] = "prog-debug"
        else:
            config["COMPILER_FLAGS"] = "-std=c++23 -Wall -Wextra -Wpedantic -O3 -Wno-language-extension-token"
            config["OBJECT_DIR"] = "./objects/"
            config["EXE_FILE"] = "prog"

        if args.o:
            config["EXE_FILE"] = args.o

        if sys.platform == "win32":
            config["EXE_FILE"] += ".exe"

        make.parse_dict(config)
        make.execute("build")


if __name__ == "__main__":
    main()
