COMPILER: "clang++"
FLAGS: "-std=c++17 -Wall -Wextra -Wpedantic -g -DDEBUG"

EXE_DIR: "./bin"
EXE_FILE: "splay_tree_test"

SOURCE_MAIN: "splay_tree_test.cpp"
SOURCE_DIR: "./src/"
SOURCE_EXT: "cpp"
HEADER_DIR: "./include/"
HEADER_EXT: "hpp"
OBJECT_DIR: "./objects/"
OBJECT_EXT: "o"

OTHER_INCLUDES: ""